# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20180223_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
