# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
