# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
