# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20180329_1239'),
        ('recipe', '0009_auto_20180329_2133'),
    ]

    operations = [
    ]
