# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersistentIngredients',
            new_name='PersistentIngredient',
        ),
    ]
