# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_time', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.CharField(max_length=200)),
                ('successful', models.BooleanField()),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
