# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperesult_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='job_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
