# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraperesult_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='error_trace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
