# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scraperesult_error_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperesult',
            name='error',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='error_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
